language: python
matrix:
  include:
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    dist: xenial
    env: TOXENV=py37

install:
  - pip install -U tox

script:
  - tox
